### ISSUE TITLE
Only Preserve Queryset Order for Ordering Filter

### ISSUE THREAD

**Issue by ericziethen** [ericziethen/django-property-filter#144]
- [x] Check what django_filter does when Mixing Ordering Filter and other Filters
- [x] When calling filter_qs_by_pk_list -> build_limited_filter_expr handle sorting if enabled by argument (default False)
- [x] ~~~ReRun Filter Performances~~ Later, some issues need to be resolved first

**Comment by ericziethen** [comment]
# TODO
            '''
                - 1.) Find out how django_filter behaves if Mixed and Ordering Filter and other filters are defined
                - 2.) Define some new Tests to Emulate the Mixed Sorting Behaviour
                - 3.) Emulate the same behaviour as filter and pass to filter_qs_by_pk_list optional boolean to preserve ()
                - 4.) TEST FIRST - Modify filter_qs_by_pk_list to allow preserving order if specified
            '''
