### ISSUE TITLE
Enhance Documentation

### ISSUE THREAD

**Issue by ericziethen** [ericziethen/django-property-filter#51]
### HOW IT WORKS
- [x] Explain Better the difference to django-filter
- [x] Explain Non DB Values Usage and Filter
- [x] explain filter in memory
- [x] Map Django-filter filters to Property Filters
### FILTER OVERVIEW
- [x] Table/Matrix with all supported Lookupvalues, highlight the default lookup
- [x] Point out Which Filters cannot be declared Implicitly, e.g. ChoiceFilter -> Maybe use a Matrix?
### LIMITATIONS and DRAWBACKS
- [x] explain filter in memory, so potentially issues for very large data sets
- [x] Document drawbacks of properties, unexpected file types
- [x] Document slower, in memory, large set, type convertions might reduce speed
- [x] document sqlite limitations, e.g. 999 max params limit, or higher depending on sqlite version...
- [x] Mention if any Filters are particular slow, like Using AllValue and AllValueMultipleChoice, document the field property to create a form and mixing filters, slow if large numbers
### TIPS
- [x] ~Guideline on how to select the correct filter~
### DEV TOOLS
- [x] ~Add Section how to Run Benchmarks in Dev Documentation~
### TODO
- [x] ~Highlight Supported Fields (See django-filter doc for details) - Highlight Supporting same fields~
- [x] ~Add limitations also to Readme.MD~
- [x] Review Content
### CODE DOCUMENTATION
- [x] ~document mixins in code properly, purpose, Inheritance Structure (Mirroring django filters) ...~
